// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This is a placeholder. 
    // You MUST run 'flutterfire configure' to generate the real configuration.
    throw UnimplementedError(
      'DefaultFirebaseOptions are not configured for this project. '
      'Run "flutterfire configure" in your terminal to generate this file.',
    );
  }
}
